### ISSUE TITLE
ERROR 42703 (undefined_column) column i0.list_id does not exist

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/time-mvp-phoenix#13]
One downside of associating `items` to `lists`
https://github.com/nelsonic/time-mvp-phoenix#associate-items-with-a-list

is that now I cannot _view_ an item without it being associated with a list ...
![image](https://user-images.githubusercontent.com/194400/65717013-3deb6a80-e098-11e9-8fb7-125a56d6efaf.png)

I can still _create_ an `item`:
![image](https://user-images.githubusercontent.com/194400/65717056-578cb200-e098-11e9-951c-7317c63cb32c.png)

But attempting to view it http://localhost:4000/items/2 results in the `ERROR 42703` ...
So we need to _automatically_ insert a row into `list_items` each time an item is created ...

**Comment by nelsonic** [comment]
```
  1) test items delete_item/1 deletes the item (App.CtxTest)
     test/app/ctx_test.exs:244
     Expected exception Ecto.NoResultsError but got Postgrex.Error (ERROR 42703 (undefined_column) column i0.list_id does not exist

         query: SELECT i0."id", i0."text", i0."person_id", i0."status", i0."kind", i0."list_id", i0."inserted_at", i0."updated_at" FROM "items" AS i0 WHERE (i0."id" = $1))
     code: assert_raise Ecto.NoResultsError, fn -> Ctx.get_item!(item.id) end
     stacktrace:
       (ecto_sql) lib/ecto/adapters/sql.ex:629: Ecto.Adapters.SQL.raise_sql_call_error/1
       (ecto_sql) lib/ecto/adapters/sql.ex:562: Ecto.Adapters.SQL.execute/5
       (ecto) lib/ecto/repo/queryable.ex:177: Ecto.Repo.Queryable.execute/4
       (ecto) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
       (ecto) lib/ecto/repo/queryable.ex:105: Ecto.Repo.Queryable.one!/3
       test/app/ctx_test.exs:247: (test)

...


 10) test edit item renders form for editing chosen item (AppWeb.ItemControllerTest)
     test/app_web/controllers/item_controller_test.exs:49
     ** (Postgrex.Error) ERROR 42703 (undefined_column) column i0.list_id does not exist

         query: SELECT i0."id", i0."text", i0."person_id", i0."status", i0."kind", i0."list_id", i0."inserted_at", i0."updated_at" FROM "items" AS i0 WHERE (i0."id" = $1)

.................

Finished in 0.9 seconds
99 tests, 10 failures
```
