### ISSUE TITLE
Lotsa Warnings + Postgrex.Error 42P07 😕 

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/time-mvp-phoenix#9]
While attempting to run the stock tests the app compilation fails: 

```
Compiling 35 files (.ex)
warning: function AppWeb.Router.Helpers.item_path/2 is undefined or private. Did you mean one of:

      * page_path/2
      * page_path/3

Found at 6 locations:
  lib/app_web/controllers/item_controller.ex:60
  lib/app_web/templates/item/edit.html.eex:5
  lib/app_web/templates/item/index.html.eex:26
  lib/app_web/templates/item/new.html.eex:3
  lib/app_web/templates/item/new.html.eex:5
  lib/app_web/templates/item/show.html.eex:13

warning: function AppWeb.Router.Helpers.item_path/3 is undefined or private. Did you mean one of:

      * page_path/2
      * page_path/3

Found at 7 locations:
  lib/app_web/controllers/item_controller.ex:22
  lib/app_web/controllers/item_controller.ex:47
  lib/app_web/templates/item/edit.html.eex:3
  lib/app_web/templates/item/index.html.eex:17
  lib/app_web/templates/item/index.html.eex:18
  lib/app_web/templates/item/index.html.eex:19
  lib/app_web/templates/item/show.html.eex:12

warning: function AppWeb.Router.Helpers.kind_path/2 is undefined or private
Found at 6 locations:
  lib/app_web/controllers/kind_controller.ex:60
  lib/app_web/templates/kind/edit.html.eex:5
  lib/app_web/templates/kind/index.html.eex:26
  lib/app_web/templates/kind/new.html.eex:3
  lib/app_web/templates/kind/new.html.eex:5
  lib/app_web/templates/kind/show.html.eex:13

warning: function AppWeb.Router.Helpers.kind_path/3 is undefined or private
Found at 7 locations:
  lib/app_web/controllers/kind_controller.ex:22
  lib/app_web/controllers/kind_controller.ex:47
  lib/app_web/templates/kind/edit.html.eex:3
  lib/app_web/templates/kind/index.html.eex:17
  lib/app_web/templates/kind/index.html.eex:18
  lib/app_web/templates/kind/index.html.eex:19
  lib/app_web/templates/kind/show.html.eex:12

warning: function AppWeb.Router.Helpers.list_path/2 is undefined or private. Did you mean one of:

      * static_path/2

Found at 6 locations:
  lib/app_web/controllers/list_controller.ex:60
  lib/app_web/templates/list/edit.html.eex:5
  lib/app_web/templates/list/index.html.eex:26
  lib/app_web/templates/list/new.html.eex:3
  lib/app_web/templates/list/new.html.eex:5
  lib/app_web/templates/list/show.html.eex:13

warning: function AppWeb.Router.Helpers.list_path/3 is undefined or private. Did you mean one of:

      * static_path/2

Found at 7 locations:
  lib/app_web/controllers/list_controller.ex:22
  lib/app_web/controllers/list_controller.ex:47
  lib/app_web/templates/list/edit.html.eex:3
  lib/app_web/templates/list/index.html.eex:17
  lib/app_web/templates/list/index.html.eex:18
  lib/app_web/templates/list/index.html.eex:19
  lib/app_web/templates/list/show.html.eex:12

warning: function AppWeb.Router.Helpers.person_path/2 is undefined or private. Did you mean one of:

      * page_path/2
      * page_path/3

Found at 6 locations:
  lib/app_web/controllers/person_controller.ex:60
  lib/app_web/templates/person/edit.html.eex:5
  lib/app_web/templates/person/index.html.eex:40
  lib/app_web/templates/person/new.html.eex:3
  lib/app_web/templates/person/new.html.eex:5
  lib/app_web/templates/person/show.html.eex:48

warning: function AppWeb.Router.Helpers.person_path/3 is undefined or private. Did you mean one of:

      * page_path/2
      * page_path/3

Found at 7 locations:
  lib/app_web/controllers/person_controller.ex:22
  lib/app_web/controllers/person_controller.ex:47
  lib/app_web/templates/person/edit.html.eex:3
  lib/app_web/templates/person/index.html.eex:31
  lib/app_web/templates/person/index.html.eex:32
  lib/app_web/templates/person/index.html.eex:33
  lib/app_web/templates/person/show.html.eex:47

warning: function AppWeb.Router.Helpers.status_path/2 is undefined or private. Did you mean one of:

      * static_path/2

Found at 6 locations:
  lib/app_web/controllers/status_controller.ex:60
  lib/app_web/templates/status/edit.html.eex:5
  lib/app_web/templates/status/index.html.eex:26
  lib/app_web/templates/status/new.html.eex:3
  lib/app_web/templates/status/new.html.eex:5
  lib/app_web/templates/status/show.html.eex:13

warning: function AppWeb.Router.Helpers.status_path/3 is undefined or private. Did you mean one of:

      * static_path/2

Found at 7 locations:
  lib/app_web/controllers/status_controller.ex:22
  lib/app_web/controllers/status_controller.ex:47
  lib/app_web/templates/status/edit.html.eex:3
  lib/app_web/templates/status/index.html.eex:17
  lib/app_web/templates/status/index.html.eex:18
  lib/app_web/templates/status/index.html.eex:19
  lib/app_web/templates/status/show.html.eex:12

warning: function AppWeb.Router.Helpers.timer_path/2 is undefined or private. Did you mean one of:

      * static_path/2

Found at 6 locations:
  lib/app_web/controllers/timer_controller.ex:60
  lib/app_web/templates/timer/edit.html.eex:5
  lib/app_web/templates/timer/index.html.eex:28
  lib/app_web/templates/timer/new.html.eex:3
  lib/app_web/templates/timer/new.html.eex:5
  lib/app_web/templates/timer/show.html.eex:18

warning: function AppWeb.Router.Helpers.timer_path/3 is undefined or private. Did you mean one of:

      * static_path/2

Found at 7 locations:
  lib/app_web/controllers/timer_controller.ex:22
  lib/app_web/controllers/timer_controller.ex:47
  lib/app_web/templates/timer/edit.html.eex:3
  lib/app_web/templates/timer/index.html.eex:19
  lib/app_web/templates/timer/index.html.eex:20
  lib/app_web/templates/timer/index.html.eex:21
  lib/app_web/templates/timer/show.html.eex:17

Generated app app
** (Postgrex.Error) ERROR 42P07 (duplicate_table) relation "kinds" already exists
    (ecto_sql) lib/ecto/adapters/sql.ex:629: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql) lib/ecto/adapters/sql.ex:716: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql) lib/ecto/migration/runner.ex:338: Ecto.Migration.Runner.log_and_execute_ddl/3
    (ecto_sql) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
    (stdlib) timer.erl:166: :timer.tc/1
```

Going to debug it but wanted to open an issue to log my progress _first_. 👍

**Comment by nelsonic** [comment]
Going to _start_ with the error and work _back_ to the warnings ...
```
ERROR 42P07 (duplicate_table) relation "kinds" already exists
```
Searching for: (_without the table name_)
```
ERROR 42P07 (duplicate_table) relation already exists
```

**Comment by nelsonic** [comment]
Thankfully I've seen this error before and I logged my solution: https://github.com/dwyl/phoenix-ecto-append-only-log-example/issues/25#issuecomment-485757533 🎉 

Steps:
```
psql -U postgres -c 'DROP DATABASE IF EXISTS app_dev;'
psql -U postgres -c 'DROP DATABASE IF EXISTS app_test;'
mix ecto.create
mix test
```
No longer have the database issue, but instead of _warnings_ for the missing path functions,
we now have _lots_ of failing tests:

```
  1) test delete person deletes chosen person (AppWeb.PersonControllerTest)
     test/app_web/controllers/person_controller_test.exs:75
     ** (UndefinedFunctionError) function AppWeb.Router.Helpers.person_path/3 is undefined or private
     code: conn = delete(conn, Routes.person_path(conn, :delete, person))
     stacktrace:
       (app) AppWeb.Router.Helpers.person_path(%Plug.Conn{adapter: {Plug.Adapters.Test.Conn, :...}, assigns: %{}, before_send: [], body_params: %Plug.Conn.Unfetched{aspect: :body_params}, cookies: %Plug.Conn.Unfetched{aspect: :cookies}, halted: false, host: "www.example.com", method: "GET", owner: #PID<0.532.0>, params: %Plug.Conn.Unfetched{aspect: :params}, path_info: [], path_params: %{}, port: 80, private: %{phoenix_recycled: true, plug_skip_csrf_protection: true}, query_params: %Plug.Conn.Unfetched{aspect: :query_params}, query_string: "", remote_ip: {127, 0, 0, 1}, req_cookies: %Plug.Conn.Unfetched{aspect: :cookies}, req_headers: [], request_path: "/", resp_body: nil, resp_cookies: %{}, resp_headers: [{"cache-control", "max-age=0, private, must-revalidate"}], scheme: :http, script_name: [], secret_key_base: nil, state: :unset, status: nil}, :delete, %App.Ctx.Person{__meta__: #Ecto.Schema.Metadata<:loaded, "people">, email: "some email", email_hash: "some email_hash", familyName: "some familyName", givenName: "some givenName", id: 8, inserted_at: ~N[2019-09-25 09:05:28], key_id: 42, kind: nil, password_hash: "some password_hash", status: nil, updated_at: ~N[2019-09-25 09:05:28], username: "some username", username_hash: "some username_hash"})
       test/app_web/controllers/person_controller_test.exs:76: (test)

...

 48) test edit kind renders form for editing chosen kind (AppWeb.KindControllerTest)
     test/app_web/controllers/kind_controller_test.exs:49
     ** (UndefinedFunctionError) function AppWeb.Router.Helpers.kind_path/3 is undefined or private
     code: conn = get(conn, Routes.kind_path(conn, :edit, kind))
     stacktrace:
       (app) AppWeb.Router.Helpers.kind_path(%Plug.Conn{adapter: {Plug.Adapters.Test.Conn, :...}, assigns: %{}, before_send: [], body_params: %Plug.Conn.Unfetched{aspect: :body_params}, cookies: %Plug.Conn.Unfetched{aspect: :cookies}, halted: false, host: "www.example.com", method: "GET", owner: #PID<0.636.0>, params: %Plug.Conn.Unfetched{aspect: :params}, path_info: [], path_params: %{}, port: 80, private: %{phoenix_recycled: true, plug_skip_csrf_protection: true}, query_params: %Plug.Conn.Unfetched{aspect: :query_params}, query_string: "", remote_ip: {127, 0, 0, 1}, req_cookies: %Plug.Conn.Unfetched{aspect: :cookies}, req_headers: [], request_path: "/", resp_body: nil, resp_cookies: %{}, resp_headers: [{"cache-control", "max-age=0, private, must-revalidate"}], scheme: :http, script_name: [], secret_key_base: nil, state: :unset, status: nil}, :edit, %App.Ctx.Kind{__meta__: #Ecto.Schema.Metadata<:loaded, "kinds">, id: 11, inserted_at: ~N[2019-09-25 09:05:28], text: "some text", updated_at: ~N[2019-09-25 09:05:28]})
       test/app_web/controllers/kind_controller_test.exs:50: (test)

.

Finished in 0.6 seconds
99 tests, 48 failures
````

So I've got to figure out why a _freshly_ created app with schemas created using `gen` command creates an app with references to undefined functions ... 🙄 🔍

**Comment by nelsonic** [comment]
After _much_ Googling, reading issue threads, forum topics and StackOverflow answers e.g:
+ https://github.com/smpallen99/ex_admin/issues/321
+ https://stackoverflow.com/questions/40561203/module-myapp-router-helpers-is-not-loaded-and-could-not-be-found
+ https://elixirforum.com/t/programming-phoenix-error-function-routes-user-path-3-is-undefined-module-routes-is-not-available/14526/12

I found @jakubgarfield's post from 2015 https://chodounsky.net/2015/06/02/adding-ecto-model-in-phoenix-throws-path-slash-3-undefined which is _ancient_ but had the simple advice:

make sure that you add resource to your router.ex file.

```
resources "/storages", StorageController
```

So I added a `resources` line for each schema to `lib/app_web/router.ex`:

**`BEFORE`**:
```elixir
  scope "/", AppWeb do
    pipe_through :browser

    get "/", PageController, :index
  end
```

***`AFTER`***:
```elixir
  scope "/", AppWeb do
    pipe_through :browser

    get "/", PageController, :index

    # generic resources for schemas:
    resources "/items", ItemController
    resources "/kinds", KindController
    resources "/lists", ListController
    resources "/person", PersonController
    resources "/status", StatusController
    resources "/timers", TimerController
  end
```

And now when I run the tests, they pass!
```
 mix test
...................................................................................................

Finished in 0.8 seconds
99 tests, 0 failures

Randomized with seed 116948
```

_Boom_! 💥 
Thanks to @jakubgarfield for taking the time to _publish_ the simple solution. 🚀
